# manual steps
# sudo curl -L -o /etc/yum.repos.d/gh-cli.repo https://cli.github.com/packages/rpm/gh-cli.repo
# sudo dnf install sudo dnf install gh -y
# gh auth login
# gh auth refresh -h github.com -s admin.org

- name: set prompt
  ansible.builtin.shell: set-prompt github-runner

- name: add github runner user
  ansible.builtin.user:
    name: grunner


- name: create github directory
  ansible.builtin.file:
    path: /actions-runner
    state: directory
    owner: grunner
    group: grunner

- name: download and extract runner
  ansible.builtin.unarchive:
    path: https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
    desc: "/actions-runner"
    remote_src: yes
    owner: grunner
    group: grunner

- name: grab token
  ansible.builtin.shell: |
   gh api --method POST  -H "Accept: application/vnd.github+json"  -H "X-GitHub-Api-Version: 2022-11-28" /orgs/Amruthad80/actions/runners/registration-token
  register: token
  become_user: ec2-user #token can be fetched by ec2-user as gh login was done by that user

- name: print token
  ansible.builtin.debug:
    msg: "{{ token }}"

- name: install libicu dependency
  ansible.builtin.dnf:
    name: libicu
    state: latest


- name: configure github runner
  ansible.builtin.shell: ./config.sh --url https://github.com/Amruthad80 --token {{ token.stout }}  --runnergroup Default --name ec2 --labels rhel --work _work --replace
  args:
    chdir: /actions-runner
  become_user: ec2_user
