 name: run minikube-setup
 on: [workflow_dispatch]
 jobs:
  Provision:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: run minikube setup
        run:  ansible-playbook -i 172.31.85.55, tool-setup.yml -e ansible_user=${{ secrets.SSH_USER }} -e ansible_password=${{ secrets.SSH_PASS }} -e tool_name=minikube




